import { createFileRoute, Link } from '@tanstack/react-router';
import { usePageTitle } from '@/hooks/usePageTitle';

export const Route = createFileRoute('/terms')({
  component: TermsOfService,
});

function TermsOfService() {
  usePageTitle('Terms of Service');

  return (
    <div className="min-h-dvh bg-background">
      <nav className="flex items-center justify-between px-6 py-5 sm:px-10">
        <Link
          to="/"
          className="flex items-center gap-2.5 text-xl font-semibold tracking-tight"
          style={{ fontFamily: 'Fraunces, serif' }}
        >
          <img
            src="/favicon.png"
            alt="Simversity"
            className="h-8 w-auto"
            width={32}
            height={32}
          />
          Simversity
        </Link>
      </nav>

      <main className="mx-auto max-w-3xl px-6 py-12 sm:px-10">
        <h1
          className="text-3xl font-light tracking-tight sm:text-4xl"
          style={{ fontFamily: 'Fraunces, serif' }}
        >
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 1, 2026
        </p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="text-lg font-semibold">1. Acceptance</h2>
            <p className="mt-2">
              By creating an account or using Simversity, you agree to these
              Terms of Service and our{' '}
              <Link
                to="/privacy"
                className="text-primary underline-offset-4 hover:underline"
              >
                Privacy Policy
              </Link>
              . If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">2. Description of Service</h2>
            <p className="mt-2">
              Simversity is an AI-powered teaching simulator that allows
              educators to practice responding to students with common
              misconceptions. The service generates simulated student responses
              and observer feedback using artificial intelligence. AI-generated
              responses should not be treated as professional pedagogical
              advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">3. Accounts</h2>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                You must provide accurate information when creating an account.
              </li>
              <li>
                You are responsible for maintaining the security of your
                credentials.
              </li>
              <li>One account per person. Do not share your login.</li>
              <li>
                You must be at least 18 years old or the age of majority in your
                jurisdiction.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">4. Acceptable Use</h2>
            <p className="mt-2">You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                Attempt to extract, reverse-engineer, or manipulate the AI
                system prompts.
              </li>
              <li>
                Use the service to generate harmful, abusive, or inappropriate
                content.
              </li>
              <li>
                Interfere with the service's operation or other users'
                experience.
              </li>
              <li>
                Use automated tools to access the service beyond normal usage
                patterns.
              </li>
              <li>
                Circumvent rate limits, access controls, or other security
                measures.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">5. Content Ownership</h2>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Your content:</strong> you retain ownership of the
                messages you write during practice conversations.
              </li>
              <li>
                <strong>AI-generated content:</strong> observer feedback and
                student responses are generated by AI and provided for your
                educational use. You may use this content for personal
                professional development, portfolios, and teaching improvement.
              </li>
              <li>
                <strong>Scenarios and personas:</strong> course content,
                scenarios, and student personas are the intellectual property of
                Simversity.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              6. AI Limitations & Disclaimer
            </h2>
            <p className="mt-2">
              AI-generated responses (student personas, observer feedback) are
              simulations. They may occasionally produce inaccurate, incomplete,
              or inappropriate content. Simversity does not guarantee the
              pedagogical accuracy of AI outputs. Observer feedback is intended
              as a reflective tool, not as a formal evaluation of your teaching
              ability.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">7. Availability</h2>
            <p className="mt-2">
              We strive to keep Simversity available but do not guarantee
              uninterrupted access. The service depends on third-party AI
              providers and may be temporarily unavailable during maintenance or
              outages. We may impose usage limits to manage costs and ensure
              fair access.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              8. Limitation of Liability
            </h2>
            <p className="mt-2">
              Simversity is provided "as is" without warranties of any kind. To
              the maximum extent permitted by law, we are not liable for any
              indirect, incidental, or consequential damages arising from your
              use of the service. Our total liability is limited to the amount
              you paid for the service (if any) in the 12 months preceding the
              claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">9. Termination</h2>
            <p className="mt-2">
              We may suspend or terminate your account if you violate these
              terms. You may delete your account at any time by contacting us.
              Upon termination, your data will be handled in accordance with our
              Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">10. Changes</h2>
            <p className="mt-2">
              We may update these terms from time to time. We will notify
              registered users of material changes via email. Continued use
              after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">11. Contact</h2>
            <p className="mt-2">
              If you have questions about these terms, contact us at{' '}
              <a
                href="mailto:support@simversity.app"
                className="text-primary underline-offset-4 hover:underline"
              >
                support@simversity.app
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-12 border-t border-border pt-6 text-sm text-muted-foreground">
          <Link to="/privacy" className="hover:text-primary hover:underline">
            Privacy Policy
          </Link>
        </div>
      </main>
    </div>
  );
}
